In [1]:
print("Hello World!")
print("Hello World!", quote = FALSE)
print(paste("How","are","you?"))

[1] "Hello World!"
[1] Hello World!
[1] "How are you?"


In [2]:
x = c(1,2,3)
y = c(4,5,6)
x+y

[1] 5 7 9

In [3]:
x = c(1,2,NA,3,4)
mean(x)
mean(x, na.rm=TRUE)
sum(x, na.rm=TRUE)

[1] NA

[1] 2.5

[1] 10

In [4]:
# Get random number from uniform distribution between 0 and 1
runif(1)
runif(3)
runif(3, min=5, max=10)    # define the range between 5 and 10

[1] 0.8175773

[1] 0.2099878 0.5094510 0.1506517

[1] 9.641857 9.698727 8.932558

In [5]:
# Get random number from normal distribution
rnorm(1)  # 0 mean, 1 standard deviation
rnorm(3)
rnorm(3, mean=10, sd=2)    # provide our own mean and standard deviation

[1] 0.02832869

[1] -0.4959071 -1.3343932 -0.4075418

[1] 9.643484 8.797300 8.793114

In [6]:
x = c(1,5,3,7,9,4,0)
min(x)
max(x)
range(x)
sort(x)
sort(x, decreasing=TRUE)
x
order(x)  # returns indices of values assuming sorted

[1] 0

[1] 9

[1] 0 9

[1] 0 1 3 4 5 7 9

[1] 9 7 5 4 3 1 0

[1] 1 5 3 7 9 4 0

[1] 7 1 3 6 2 4 5

In [7]:
# Compute factorial with recursion
recur_factorial <- function(n) {
    if(n <= 1) {
        return(1)
    } else { 
        return(n * recur_factorial(n-1))
    }
}
recur_factorial(5)

[1] 120

In [5]:
# Matrix algebra
X <- matrix(1:4, nrow=2, ncol=2, byrow=FALSE, dimnames = NULL)
X
X <- matrix(1:4, nrow=2, ncol=2, byrow=FALSE, list(c("row1", "row2"),
                               c("C.1", "C.2")))
X
Y <- matrix(5:8, nrow=2, ncol=2, byrow=TRUE, dimnames = NULL)
Y

[,1] [,2]
[1,] 1    3   
[2,] 2    4

C.1 C.2
row1 1   3  
row2 2   4

[,1] [,2]
[1,] 5    6   
[2,] 7    8

In [9]:
X + Y
X - Y
X * Y
X / Y
X ^ Y

[,1] [,2]
[1,] 6     9  
[2,] 9    12

[,1] [,2]
[1,] -4   -3  
[2,] -5   -4

[,1] [,2]
[1,]  5   18  
[2,] 14   32

[,1]      [,2]
[1,] 0.2000000 0.5 
[2,] 0.2857143 0.5

[,1] [,2] 
[1,]   1    729
[2,] 128  65536

In [10]:
X %*% Y

[,1] [,2]
[1,] 26   30  
[2,] 38   44

In [11]:
# Bind two matrices columnwise or rowwise
cbind(X, Y)
rbind(X, Y)

[,1] [,2] [,3] [,4]
[1,] 1    3    5    6   
[2,] 2    4    7    8

[,1] [,2]
[1,] 1    3   
[2,] 2    4   
[3,] 5    6   
[4,] 7    8

In [12]:
colMeans(X)
rowMeans(X)

[1] 1.5 3.5

[1] 2 3

In [13]:
colSums(X)
rowSums(X)

[1] 3 7

[1] 4 6

In [14]:
# Transpose
X
t(X)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 1    2   
[2,] 3    4