r에서는 변수를 객체라고 함

대소문자 구분

print 안쓰고 그대로 변수 이름 쓰면 출력



In [21]:
# ---Simple Calculations---
2 + 3sin(pi)         # 1.224606e-16
log(3)          # 1.098612 (자연로그)
log10(100)      # 2  (상용로그)
floor(3.14)     # 3  (버림)
ceiling(5.87)   # 6  (올림)
round(4.65)     # 5  (반올림)
sqrt(9)         # 3  (제곱근)
min(c(1,5,7))   # 1  (최소값)
max(c(2,6,9))   # 9  (최대값)
mean(c(3,6,9))  # 6  (평균)
sum(c(1,2,4,7)) # 14  (합계)
sd(c(1,2,3,4))  # 1.290994  (표준편차)
runif(2, 1, 10) # 난수 2개를 벡터로 생성(1 초과 10 미만)

x <- 2
y <- 3
x + y
x * y
x %/% y #나누기
x %% y #나머지
3^2 # 거듭제곱 이렇게 가능

ERROR: Error in parse(text = x, srcfile = src): <text>:2:6: 예상하지 못한 기호(symbol)입니다.
1: # ---Simple Calculations---
2: 2 + 3sin
        ^


In [22]:
# 1부터 10까지 2씩 증가하는 벡터 
s<-seq(1, 10, by=2)
s

[1] 1 3 5 7 9

In [23]:
ls()#현재까지의 모든 객체 이름 확인
objects()#이것도
rm(x)#객체 삭제

[1] "a"        "gender"   "q1"       "q2"       "q3"       "q4"      
 [7] "s"        "v"        "workshop" "x"        "y"

[1] "a"        "gender"   "q1"       "q2"       "q3"       "q4"      
 [7] "s"        "v"        "workshop" "x"        "y"

## 스칼라와 벡터 

## 스칼라
### 3가지 값 할당 가능
### x <- 2.7         # 실수
### y <- "string"    # 문자열
### z <- FALSE       # 논리값

## 벡터 - 스칼라에 순서를 가지고 만든 거


In [24]:
y <- 1.5:4.9     # 1.5 2.5 3.5 4.5 1단위로
y
v <- c(1,2,3)
v <- v+1 #벡터에도 산술연산자 사용 가능
v
c(a= c(1,2,3))#이름 붙여 나오기


[1] 1.5 2.5 3.5 4.5

[1] 2 3 4

a1 a2 a3 
 1  2  3

In [2]:
# Vectors
workshop <- c(1, 2, 1, 2, 1, 2, 1, 2)
summary(workshop)
print(workshop)
x<- "df"
cat(workshop,x)#한번에 여러개 출력 가능, 개행하지 않음 '\n' string으로 넣으면 개행 됨
workshop
 
gender <- c("f", "f", "f", NA, "m", "m", "m", "m")#NA는 m일 수도 있고 f일수도 있는 x 그
q1 <- c(1, 2, 2, 3, 4, 5, 5, 4)
q2 <- c(1, 1, 2, 1, 5, 4, 3, 5)
q3 <- c(5, 4, 4,NA, 2, 5, 4, 5)
q4 <- c(1, 1, 3, 3, 4, 5, 4, 5)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.0     1.0     1.5     1.5     2.0     2.0 

[1] 1 2 1 2 1 2 1 2
1 2 1 2 1 2 1 2 df

[1] 1 2 1 2 1 2 1 2

In [3]:
# Selecting Elements of Vectors
q1[5]#index가 1부터 시작함 0이 아니라
q1[ c(5, 6, 7, 8) ]# 한개이상은 이렇게 찾아야함.index 번호로 검색 하려면
#[]는 index searching. 벡터에 있는 순서의 값들 출력
print(q1)
q1[5:8]

[1] 4

[1] 4 5 5 4

[1] 1 2 2 3 4 5 5 4


[1] 4 5 5 4

In [4]:
gender == "m"#gender벡터에서 조건에 맞는지 안맞는지 검사. 벡터 값의 논리값 나옴
typeof(gender == "m")
is.vector(gender == "m")
q1[gender == "m"]#true인 값들 모아서
# NA also matches "m". na.rm -> remove NA when computing mean
mean( q1[ gender == "m" ], na.rm = TRUE)#na가 가능성이 있으니 출려되는데 그래서 na.rm(remove)해서
mean( q1[ gender == "m" ])#ㅡmean은 평균 값

[1] FALSE FALSE FALSE    NA  TRUE  TRUE  TRUE  TRUE

[1] "logical"

[1] TRUE

[1] NA  4  5  5  4

[1] 4.5

[1] NA

In [5]:
# First, as a vector
workshop <- c(1, 2, 1, 2, 1, 2, 1, 2)
workshop
# Count frequency of elements in list
table(workshop)#표로 보여줌 원소의 개수를
mean(workshop)
gender[workshop == 2]#2,4,6,8에 있으니 그걸 gender에서 가지고 옴

[1] 1 2 1 2 1 2 1 2

workshop
1 2 
4 4 

[1] 1.5

[1] "f" NA  "m" "m"

c는 벡터

## factor는 vector를 레벨 정보로 가지고 있는 거

## factor는 벡터 값들을 char으로 바꿔서 넣음

# factor = vector represented using level information, levels can be used as categories 
factor는 levels 함수를 쓸 수 있게해줌

카테고리형 변수

In [6]:
# Now as a factor
workshop <- c(4, 2, 5, 2, 5, 2, 5, 3)
workshop <- factor(workshop)#원래 백터와 팩터 둘 다 가지고 있는 게 조음. factor변환하면 cahr이 되어버려서

cat("level : ", levels(workshop),"\n")#level이라는 가지는데, 이건 원소중에 중복되지 않은 것들만 뽑아줌 
cat("table : ",table(workshop),"\n")#원소의 개수 label별로
cat("summary : ",summary(workshop),"\n")#table과 동일한데 행과 열이 바뀌어 있음

level :  2 3 4 5 
table :  3 1 1 3 
summary :  3 1 1 3 


## as.numeric 하면
### factor는 char이기 때문에, 크기 순서대로 임의로 1,2,3,4이렇게 부여함(숫자순, 알파벳순), 같은 label이면 같은 숫자를 줌
### 그래서 평균은 변환된 숫자의 평균. 원래 숫자가 아니라.

In [7]:
mean(workshop) #에러 - facor로 되면 원소들 char 레이블로 생각함
#generates error now since factored output is character
typeof(workshop)#int라고 뜨지만 아님.
as.numeric(workshop)
mean(as.numeric(workshop))#as.numeric은 숫자로 바꿔줌
# factor workshop can be accessed by both strings and integers due to levels


Warning message in mean.default(workshop):
"argument is not numeric or logical: returning NA"

[1] NA

[1] "integer"

[1] 3 1 4 1 4 1 4 2

[1] 2.5

In [8]:
xx<-factor(c("k","K","k","ff"))
as.numeric(xx)
mean(as.numeric(xx))
#검색은 둘 다 가능
gender[workshop == 2]
gender[workshop == "2"]

[1] 2 3 2 1

[1] 2

[1] "f" NA  "m"

[1] "f" NA  "m"

In [9]:
xv <- c("A", "C", "B", "A", "A", "C", "B") 
xv
# factor = vector represented using level information, levels can be used as categories 
# vector stores all 7 strings 
#whereas factor stores only 3 strings and let vector be represented as sequence of integers
x <- factor(xv, c("A", "C"))
x
x <- factor(xv, levels = c("A", "C"))#리스트에 넣어서 비교 둘다 같은 말
x
as.numeric(x)#위에서 levels란 함수에서 각 고유한 문자들을 숫자로 가지고 있음. 그래서 a는 1 b는 2


[1] "A" "C" "B" "A" "A" "C" "B"

[1] A    C    <NA> A    A    C    <NA>
Levels: A C

[1] A    C    <NA> A    A    C    <NA>
Levels: A C

[1]  1  2 NA  1  1  2 NA

In [10]:
# different types can be in the same vector
v <- c("abc", 12, 0.456, TRUE)
v
is.vector(v)
length(v)


[1] "abc"   "12"    "0.456" "TRUE"

[1] TRUE

[1] 4

## 리스트(list)
걍 다 넣을 수 있음

In [11]:
# (3,2,1)을 3번 반복하는 벡터 작성 
vec <- rep(c(1,2,3),3)
mat <- matrix(1:12, ncol = 4)
mx <- matrix(rep(c(1,2),2), ncol =2)
MyList <- list(data1 = vec, data2 = max, data3 = mx)
MyList

$data1
[1] 1 2 3 1 2 3 1 2 3

$data2
function (..., na.rm = FALSE)  .Primitive("max")

$data3
     [,1] [,2]
[1,]    1    1
[2,]    2    2

## 데이터프레임(data frame)
### 리스트의 한 종류로 리스트에 포함된 모든 값이 길이가 같은 벡터일 때, 혹은 행의 수, 열의 수가 같은 행렬에 한해 그 리스트를 함수 data.frame()을 이용해 데이터프레임으로 변환시킬 수 있다.
행은 임의로 1,2,3,4 열은 넣을 때 이름 => 바꿀 수 있음

In [12]:
# Data Frames
mydata <- data.frame(workshop, gender, q1, q2, q3, q4)
print("mydata")
mydata
print("names of mydata") 
names(mydata)#index 각 항목 이름
print("row names of mydata")
row.names(mydata)#rownames(mydata)해도 됨
row.names(mydata) <- c("a","b","c","d","e","f","g","h")#row 이름을 정함
print("new row names of mydata")
row.names(mydata)
mydata

[1] "mydata"


workshop gender q1 q2 q3 q4
1 4        f      1  1   5 1 
2 2        f      2  1   4 1 
3 5        f      2  2   4 3 
4 2        NA     3  1  NA 3 
5 5        m      4  5   2 4 
6 2        m      5  4   5 5 
7 5        m      5  3   4 4 
8 3        m      4  5   5 5

[1] "names of mydata"


[1] "workshop" "gender"   "q1"       "q2"       "q3"       "q4"

[1] "row names of mydata"


[1] "1" "2" "3" "4" "5" "6" "7" "8"

[1] "new row names of mydata"


[1] "a" "b" "c" "d" "e" "f" "g" "h"

workshop gender q1 q2 q3 q4
a 4        f      1  1   5 1 
b 2        f      2  1   4 1 
c 5        f      2  2   4 3 
d 2        NA     3  1  NA 3 
e 5        m      4  5   2 4 
f 2        m      5  4   5 5 
g 5        m      5  3   4 4 
h 3        m      4  5   5 5

### [행:열]   [세로:가로]   [row, col]
### matrix는 cbind 
### data.frame 그냥 list넣듯 그리고 $$$씀
### list도 $ 씀

In [36]:
# Selecting components by index number
mydata[8, 6] #8th obs행, 6th var렬 row를 나타내는 abcd빼고 1234샘. 1=1 2=f
mydata[ , 6] #All obs, 6th var
mydata[ , 6][5:8] #6th var, obs 5:8 5~6행
mydata[5:8, 6] #윗 줄이랑 같은 말

[1] 5

[1] 1 1 3 3 4 5 4 5

[1] 4 5 4 5

[1] 4 5 4 5

In [37]:
# Selecting components by name
mydata$q1
mydata$q1[5:8]

[1] 1 2 2 3 4 5 5 4

[1] 4 5 5 4

In [38]:
# Example renaming gender to sex while
# creating a data frame (left as a comment)
mydata <- data.frame(workshop, sex = gender, q1, q2, q3, q4)
mydata

workshop sex q1 q2 q3 q4
1 4        f   1  1   5 1 
2 2        f   2  1   4 1 
3 5        f   2  2   4 3 
4 2        NA  3  1  NA 3 
5 5        m   4  5   2 4 
6 2        m   5  4   5 5 
7 5        m   5  3   4 4 
8 3        m   4  5   5 5

In [39]:
#매트릭스(벡터, 행개수, 열개수)
matrix(
    c(1, 2, 4, 8, 16, 32),
    nrow=2,
    ncol=3
)

[,1] [,2] [,3]
[1,] 1    4    16  
[2,] 2    8    32

In [40]:
# Matrices
 
# Creating from vectors
mymatrix <- cbind(q1, q2, q3, q4)#column bind
mymatrix
dim(mymatrix)#행과 열을 알려줌 dimension

q1 q2 q3 q4
[1,] 1  1   5 1 
[2,] 2  1   4 1 
[3,] 2  2   4 3 
[4,] 3  1  NA 3 
[5,] 4  5   2 4 
[6,] 5  4   5 5 
[7,] 5  3   4 4 
[8,] 4  5   5 5

[1] 8 4

In [41]:
# Creating from matrix function
# left as a comment so we keep
# version with names q1, q2...
#matrix(벡터, nrow=행개수, ncol=열개수)
rnames <- c("R1", "R2","R3","R4","R5", "R6","R7","R8")
cnames <- c("C1", "C2","C3","C4")
mymatrix <- matrix(
   c(1, 1, 5, 1,
     2, 1, 4, 1,
     2, 2, 4, 3,
     3, 1, NA,3,
     4, 5, 2, 4,
     5, 4, 5, 5,
     5, 3, 4, 4,
     4, 5, 5, 4),
  nrow = 8, ncol = 4,byrow = TRUE,dimnames=list(rnames, cnames))
mymatrix
#byrow = TRUE row 채우는 식

C1 C2 C3 C4
R1 1  1   5 1 
R2 2  1   4 1 
R3 2  2   4 3 
R4 3  1  NA 3 
R5 4  5   2 4 
R6 5  4   5 5 
R7 5  3   4 4 
R8 4  5   5 4

In [42]:
table(mymatrix)
mean(mymatrix, na.rm = TRUE)
# Compute correlations between columns of matrix
cor(mymatrix, use = "pairwise")#pairwise 쌍으로
cor(mymatrix, use="complete")#NA있으면 처리하는 방식

mymatrix
1 2 3 4 5 
6 4 4 9 8 

[1] 3.290323

C1         C2         C3         C4        
C1  1.0000000  0.7395179 -0.1250000  0.9055415
C2  0.7395179  1.0000000 -0.2700309  0.7968327
C3 -0.1250000 -0.2700309  1.0000000 -0.1132277
C4  0.9055415  0.7968327 -0.1132277  1.0000000

C1         C2         C3         C4        
C1  1.0000000  0.7800892 -0.1250000  0.9058216
C2  0.7800892  1.0000000 -0.2700309  0.8560993
C3 -0.1250000 -0.2700309  1.0000000 -0.1132277
C4  0.9058216  0.8560993 -0.1132277  1.0000000

In [43]:
# Selecting Subsets of Matrices
 
mymatrix[8, 4]
mymatrix[5:8, 3:4]#4*2가 나옴
mymatrix[ ,4][1:4]
mymatrix$q4  # No good! $q4 is good for dataframe
mymatrix[ ,"q4"]

[1] 4

C3 C4
R5 2  4 
R6 5  5 
R7 4  4 
R8 5  4

R1 R2 R3 R4 
 1  1  3  3

ERROR: Error in mymatrix$q4: $ operator is invalid for atomic vectors


In [44]:
# Matrix Algebra
#transpose 8*4rk 4*8이 됨
mymatrixT <- t(mymatrix)
mymatrixT

R1 R2 R3 R4 R5 R6 R7 R8
C1 1  2  2   3 4  5  5  4 
C2 1  1  2   1 5  4  3  5 
C3 5  4  4  NA 2  5  4  5 
C4 1  1  3   3 4  5  4  4

In [45]:
# Lists
mylist <- list(workshop, gender,
q1, q2, q3, q4, mymatrix)
mylist

[[1]]
[1] 4 2 5 2 5 2 5 3
Levels: 2 3 4 5

[[2]]
[1] "f" "f" "f" NA  "m" "m" "m" "m"

[[3]]
[1] 1 2 2 3 4 5 5 4

[[4]]
[1] 1 1 2 1 5 4 3 5

[[5]]
[1]  5  4  4 NA  2  5  4  5

[[6]]
[1] 1 1 3 3 4 5 4 5

[[7]]
   C1 C2 C3 C4
R1  1  1  5  1
R2  2  1  4  1
R3  2  2  4  3
R4  3  1 NA  3
R5  4  5  2  4
R6  5  4  5  5
R7  5  3  4  4
R8  4  5  5  4

In [46]:
# List, this time adding names
mylist <- list(
workshop = workshop,
gender   = gender,
q1 = q1,
q2 = q2,
q3 = q3,
q4 = q4,
mymatrix = mymatrix)
mylist

$workshop
[1] 4 2 5 2 5 2 5 3
Levels: 2 3 4 5

$gender
[1] "f" "f" "f" NA  "m" "m" "m" "m"

$q1
[1] 1 2 2 3 4 5 5 4

$q2
[1] 1 1 2 1 5 4 3 5

$q3
[1]  5  4  4 NA  2  5  4  5

$q4
[1] 1 1 3 3 4 5 4 5

$mymatrix
   C1 C2 C3 C4
R1  1  1  5  1
R2  2  1  4  1
R3  2  2  4  3
R4  3  1 NA  3
R5  4  5  2  4
R6  5  4  5  5
R7  5  3  4  4
R8  4  5  5  4

### list[$로된 항목이름]
### list[[항목의 원소접근]]

In [48]:
# Selecting components by index number.
mylist[[2]]#gender
mylist[[2]][5:8]
 
mylist[2]#이름까지 같이 나옴
mylist[2][5:8]  # Bad!#이름의 원소말이 안되니까 null 나옴 

mylist$gender[5:8]

[1] "f" "f" "f" NA  "m" "m" "m" "m"

[1] "m" "m" "m" "m"

$gender
[1] "f" "f" "f" NA  "m" "m" "m" "m"

$<NA>
NULL

$<NA>
NULL

$<NA>
NULL

$<NA>
NULL


[1] "m" "m" "m" "m"

In [31]:
# Selecting components by name.
names(mylist)
mylist$q1#matrics는 그대로 들어간 게 아니라 $로 검색이 안되지만 dataframe과 list는 가능
mylist$mymatrix[5:8, 3:4]

[1] "workshop" "gender"   "q1"       "q2"       "q3"       "q4"       "mymatrix"

[1] 1 2 2 3 4 5 5 4

C3 C4
R5 2  4 
R6 5  5 
R7 4  4 
R8 5  4

In [51]:
# A good function that just prints.
myvar <- c(1, 2, 3, 4, 5)

mystats <- function(x) {
print( mean(x, na.rm = TRUE) )
print(   sd(x, na.rm = TRUE) )
# return(0) return 값을 소괄호로 감싸야함
}#sd는 표준편차

ms <- mystats
#함수하당가능
ms(myvar)

mystats(myvar)

[1] 3
[1] 1.581139
[1] 3
[1] 1.581139


In [59]:
# A function with vector output.
mystats  <- function(x) {
mymean <- mean(x, na.rm = TRUE)
mysd   <-   sd(x, na.rm = TRUE)
c(mean = mymean, sd = mysd )#이걸 return
}
mystats(myvar)
yVector <- mystats(myvar)
#myVector

mean       sd 
3.000000 1.581139

In [41]:
# A function with list output.
mystats   <- function(x) {
myinput <- x
mymean  <- mean(x, na.rm = TRUE)
mysd    <-   sd(x, na.rm = TRUE)
list(data = myinput, mean = mymean, sd = mysd)
}
print("call mystats")
mystats(myvar)
print("call mystats and save into myStatlist")
myStatlist <- mystats(myvar)
myStatlist
print("copy mystats")
mystats#함수 그대로 찍음
print("save things into external R file")# 파일 저장
#save(mydata, mymatrix, mylist, mystats,file = "myWorkspace.RData")

[1] "call mystats"


$data
[1] 1 2 3 4 5

$mean
[1] 3

$sd
[1] 1.581139

[1] "call mystats and save into myStatlist"


$data
[1] 1 2 3 4 5

$mean
[1] 3

$sd
[1] 1.581139

[1] "copy mystats"


function(x) {
myinput <- x
mymean  <- mean(x, na.rm = TRUE)
mysd    <-   sd(x, na.rm = TRUE)
list(data = myinput, mean = mymean, sd = mysd)
}

[1] "save things into external R file"


In [42]:
myWS <- load("myWorkspace.RData")
myWS#안에 이름만 등장
mydata
mymatrix

[1] "mydata"   "mymatrix" "mylist"   "mystats"

workshop sex q1 q2 q3 q4
1 1        f   1  1   5 1 
2 2        f   2  1   4 1 
3 1        f   2  2   4 3 
4 2        NA  3  1  NA 3 
5 1        m   4  5   2 4 
6 2        m   5  4   5 5 
7 1        m   5  3   4 4 
8 2        m   4  5   5 5

[,1] [,2] [,3] [,4]
[1,] 1    1     5   1   
[2,] 2    1     4   1   
[3,] 2    2     4   3   
[4,] 3    1    NA   3   
[5,] 4    5     2   4   
[6,] 5    4     5   5   
[7,] 5    3     4   4   
[8,] 4    5     5   5

In [ ]:
#반복 loop 
i <- 0
while(i < 10) {
    i <- i + 1
}

sum <- 0
for(i in c(1, 4, 7)) {
    sum <- sum + i
}

sum <- 0
for(i in 5:15) {
    if(i%%2 == 0)
    {
        next;
    }
    if(i%%10 == 0)
    {
        break;
    }
    sum <- sum + i
}